Document: libdbi
Title: Debian libdbi Manual
Author: <insert document author here>
Abstract: This manual describes what libdbi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libdbi/libdbi.sgml.gz

Format: postscript
Files: /usr/share/doc/libdbi/libdbi.ps.gz

Format: text
Files: /usr/share/doc/libdbi/libdbi.text.gz

Format: HTML
Index: /usr/share/doc/libdbi/html/index.html
Files: /usr/share/doc/libdbi/html/*.html
