Document: libdbi-drivers
Title: Debian libdbi-drivers Manual
Author: <insert document author here>
Abstract: This manual describes what libdbi-drivers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libdbi-drivers/libdbi-drivers.sgml.gz

Format: postscript
Files: /usr/share/doc/libdbi-drivers/libdbi-drivers.ps.gz

Format: text
Files: /usr/share/doc/libdbi-drivers/libdbi-drivers.text.gz

Format: HTML
Index: /usr/share/doc/libdbi-drivers/html/index.html
Files: /usr/share/doc/libdbi-drivers/html/*.html
