Document: spidermonkey-perl
Title: Debian spidermonkey-perl Manual
Author: <insert document author here>
Abstract: This manual describes what spidermonkey-perl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spidermonkey-perl/spidermonkey-perl.sgml.gz

Format: postscript
Files: /usr/share/doc/spidermonkey-perl/spidermonkey-perl.ps.gz

Format: text
Files: /usr/share/doc/spidermonkey-perl/spidermonkey-perl.text.gz

Format: HTML
Index: /usr/share/doc/spidermonkey-perl/html/index.html
Files: /usr/share/doc/spidermonkey-perl/html/*.html
