#!/bin/sh
#CODE SOURCE: Ejabberd config (.deb file)
set -e
get_user_password()
{
  db_input high opensrf/user_password || true
  db_input high opensrf/verify_user_password || true
  db_go || true
  db_get opensrf/user_password
  PASSWORD="$RET"
  db_get opensrf/verify_user_password
  VERIFY="$RET"
  if [ "$PASSWORD" != "$VERIFY" ]; then
    db_input critical opensrf/user_nomatch || true
    db_go || true
    get_user_password
  fi
}
get_ejabber_password()
{
  db_input high opensrf/ejabber_password || true
  db_input high opensrf/verify_ejabber_password || true
  db_go || true
  db_get opensrf/ejabber_password
  PASSWORD="$RET"
  db_get opensrf/verify_ejabber_password
  VERIFY="$RET"
  if [ "$PASSWORD" != "$VERIFY" ]; then
    db_input critical opensrf/ejabber_nomatch || true
    db_go || true
    get_ejabber_password
  fi
}

get_host_fqdn()
{
	db_input medium opensrf/fqdn || true
	db_go || true
	db_get opensrf/fqdn
	if [ ! $RET ]; then
		HFQDN=$(perl -MNet::Domain -e 'print Net::Domain::hostfqdn() . "\n";')
		db_set opensrf/fqdn $HFQDN
	fi

}

. /usr/share/debconf/confmodule

get_user_password
get_ejabber_password
get_host_fqdn
exit 0

