Document: spidermonkey
Title: Debian spidermonkey Manual
Author: <insert document author here>
Abstract: This manual describes what spidermonkey is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spidermonkey/spidermonkey.sgml.gz

Format: postscript
Files: /usr/share/doc/spidermonkey/spidermonkey.ps.gz

Format: text
Files: /usr/share/doc/spidermonkey/spidermonkey.text.gz

Format: HTML
Index: /usr/share/doc/spidermonkey/html/index.html
Files: /usr/share/doc/spidermonkey/html/*.html
